
DROP INDEX IX_Campaign_PhoneNum ON dbo.Campaign
GO
ALTER TABLE dbo.Campaign ALTER COLUMN PhoneNum VARCHAR (7) NULL
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Campaign_PhoneNum ON dbo.Campaign 
(
	[PhoneNum] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
